version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: radfordhmdt.azurecr.io/wpp-photosapp
    ports:
      - '3000:3000'
    volumes:
      - ./keys:/app/keys
      - ./thumbs:/app/thumbs
      - /Users/will/Desktop/wpcrall:/photos
    env_file:
      - .env-docker